# Generated by Django 2.2.16 on 2022-04-06 03:50

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220406_0633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True),
        ),
    ]
