# Generated by Django 2.2.16 on 2022-04-10 11:52

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20220406_0650'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео на youtube или vimeo'),
        ),
        migrations.AlterField(
            model_name='post',
            name='video',
            field=embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Ссылка на видео на youtube или vimeo'),
        ),
    ]
